const SECTIONS = {
  "Getting Started": [
    "Introduction",
    "Installation",
    "Configuration",
    "Deployment",
  ],
  "Design System": ["Colors", "Typography", "Icons"],
  Components: ["Button", "Input", "Select", "Checkbox"],
  Internationalization: ["Introduction", "Setup", "Usage", "Translation"],
  Modules: [
    "Achievements",
    "Calendar",
    "Changelog",
    "Flashcard",
    "Guitar Tabs",
    "Ideabox",
    "Journal",
    "Module",
    "Music",
    "Notes",
    "Password",
    "Photos",
    "Pocketbase",
    "Project K",
    "Routes",
    "Server Status",
    "Todo List",
    "Wallet",
  ],
  "Type Interfaces": [
    "Achievements",
    "Calendar",
    "Changelog",
    "Flashcard",
    "Guitar Tabs",
    "Ideabox",
    "Journal",
    "Module",
    "Music",
    "Notes",
    "Password",
    "Photos",
    "Pocketbase",
    "Project K",
    "Routes",
    "Server Status",
    "Todo List",
    "Wallet",
  ],
};

export default SECTIONS;
